### ISSUE TITLE
DataContainer dtype conflict when live_compression=True and sensor dtype is uint32 (type promotion issue)

### ISSUE THREAD

**Issue by KarDB** [KarDB/QuPyt#26]
# Description
When using `QuPyt` with a sensor configured to output a specific datatype like `uint32`, the `DataContainer` class uses this `dtype` to initialize the internal storage. This works fine for uncompressed recordings (`live_compression: false`), as the data coming from the sensor matches the container `dtype`, allowing in-place updates and averaging.

However, when recording with `live_compression: true`, `QuPyt` calculates the mean over the spatial dimension before updating the `DataContainer`. This causes implicit type promotion by NumPy/Python to `float64`. As a result, attempting to do += of a `float64` array onto a `uint32` array raises a `TypeError`.

## Repro steps

Configure a sensor with dtype `uint32` (e.g. MockCam).

Create a measurement with `live_compression: true`.

Observe type promotion and resulting exception when updating the `DataContainer`.

**An example config file is provided below**.

## Proposed Solution

If compression is enabled, we should explicitly override the `DataContainer`’s internal `dtype` to `float64` upon creation, since:

Type promotion will always occur due to mean computation.

The primary motivation for using `uint32` (space savings) only applies to uncompressed, spatially resolved measurements.

In compressed mode, storage is already reduced, and `float64` is acceptable.

This change would prevent runtime errors and simplify `dtype` handling under compression.

```yaml
experiment_type: ODMR 
averages: 1
sensor:
  type: "MockCam"
  config:
    number_measurements: &nframes 20
    target_data_type: float64
    image_roi:
    - 100  
    - 100  
    - 0    
    - 0    
synchroniser:
  type: 'MockSynchroniser'
  config:
    address: 'TCPIP::some::INSTR'
  channel_mapping:
    MW: 0
    LASER: 8
    READ: 1
dynamic_steps: &n_dynamic_steps 10
dynamic_devices:
  mw_source: 
    address: 'TCPIP::some::INSTR'
    device_type: 'Mock'
    config:
      amplitude:
      - ['channel_2', [1, 10]]
      frequency: [2.0e9, 3.7e9]
static_devices:
  unnecessary_source:
    address: 'TCPIP::some::INSTR'
    device_type: 'Mock'
    config:
      amplitude:
      - ['channel_2', 1]
      frequency: ['channel_1', 3.7e9]
data:
  averaging_mode: 'spread'
  dynamic_steps: *n_dynamic_steps
  compress: false
  reference_channels: 2
ps_path: './dummy_sequence.py'
pulse_sequence:
  example_parameter: 20
```

```python
from qupyt.pulse_sequences.yaml_sequence import YamlSequence
def generate_sequence(params: dict):
    return gen_esr(
        params.get('example_parameter', 10),
    )

def gen_esr(
    example_parameter
) -> dict:
    esr = YamlSequence(duration=example_parameter)
    esr.sequencing_order = []
    esr.sequencing_repeats = []
    esr.write()
    return {}
```
